version: '3'
services:
   db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - dbvolume:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
   webserver:
     image: acirulis/wd-webdev-auto
     # build: .
     volumes:
       - ./webroot:/var/www/html
       - ./sites-enabled:/etc/nginx/sites-enabled
     command: /root/startup.sh
     # restart: on-failure
     ports:
       - "80:80"
       - "443:443"
     depends_on:
        - db
volumes:
  dbvolume:
