version: '2'
services:
   db:
      container_name: wd-mysql55
      image: mysql:5.5
      ports:
        - "3306:3306"
      volumes:
        - dbvolume55:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
   webserver:
     container_name: wd-apache
     image: acirulis/wd-webdev-auto:php-apache  
     # build: .
     volumes:
       - ./webroot:/var/www/html
       - ./sites-enabled:/etc/apache2/sites-enabled
       - ./certs:/etc/ssl/private
     command: /root/startup.sh
     # restart: on-failure
     #uncomment two following lines on linux and append with your host main IP to enable Xdebug
     #extra_hosts:
     #   - "host.docker.internal:192.168.1.133"
     ports:
       - "80:80"
       - "443:443"
     depends_on:
        - db
volumes:
  dbvolume55:
