 version: '3'
 services:
   # db:
   #   image: postgres
   webserver:
     # image: acirulis/wd-webdev-auto
     build: .
     volumes:
       - ./webroot:/var/www/html
       - ./sites-enabled:/etc/nginx/sites-enabled
     #command: service nginx start
     restart: on-failure
     ports:
       - "80:80"
       - "443:443"
       - "3306:3306"
     # depends_on:
     #   - db
